---

# The following variables are optional
#   tags: {"dxOwningTeam":"DemoX","dxEnvironment":"development",...} JSON list of tags    

- debug:
    msg: Configuring NR Nagios On-Host integration

- block:
  - name: Create Nagios integration config file
    copy:
      src: nagios-config.yml
      dest: /etc/newrelic-infra/integrations.d/nagios-config.yml

  - name: Create Nagios service checks file
    copy:
      src: service-checks.yml
      dest: /etc/newrelic-infra/integrations.d/service-checks.yml
      mode: 0600

  - name: Create Nagios service checks directory
    file:
      path: /usr/local/nagios/libexec/
      state: directory

  - name: Add all Nagios service checks
    copy:
      src: "{{ item }}"
      dest: /usr/local/nagios/libexec/
      mode: 0777
    with_fileglob:
      - "../templates/check_*"

  - name: Add tags header
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "  {{item.key}}: {{item.value}}"
      insertafter: 'custom_attributes:'
    loop: "{{ (tags|default({}))|dict2items }}"
    when: tags is defined
    
  become: yes   
    